//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bibliothiki.ReservationsManageReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReservationsManageReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UserReservationsManage", ReplyAction="http://tempuri.org/IService1/UserReservationsManageResponse")]
        string[] UserReservationsManage(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UserReservationsManage", ReplyAction="http://tempuri.org/IService1/UserReservationsManageResponse")]
        System.Threading.Tasks.Task<string[]> UserReservationsManageAsync(string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : bibliothiki.ReservationsManageReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<bibliothiki.ReservationsManageReference.IService1>, bibliothiki.ReservationsManageReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] UserReservationsManage(string username) {
            return base.Channel.UserReservationsManage(username);
        }
        
        public System.Threading.Tasks.Task<string[]> UserReservationsManageAsync(string username) {
            return base.Channel.UserReservationsManageAsync(username);
        }
    }
}
