//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bibliothiki.BookAvailabilityReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BookAvailabilityReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BookAvailability", ReplyAction="http://tempuri.org/IService1/BookAvailabilityResponse")]
        string[] BookAvailability(string book, string startingdate, string endingdate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/BookAvailability", ReplyAction="http://tempuri.org/IService1/BookAvailabilityResponse")]
        System.Threading.Tasks.Task<string[]> BookAvailabilityAsync(string book, string startingdate, string endingdate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : bibliothiki.BookAvailabilityReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<bibliothiki.BookAvailabilityReference.IService1>, bibliothiki.BookAvailabilityReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] BookAvailability(string book, string startingdate, string endingdate) {
            return base.Channel.BookAvailability(book, startingdate, endingdate);
        }
        
        public System.Threading.Tasks.Task<string[]> BookAvailabilityAsync(string book, string startingdate, string endingdate) {
            return base.Channel.BookAvailabilityAsync(book, startingdate, endingdate);
        }
    }
}
